#!/bin/bash
lib="/usr/lib"
python="${lib}/python3/dist-packages/MonitoringServerConnection"
echo 'from MonitoringServerConnection.MonitoringServerConnection import MonitoringServerConnection' >"${python}/__init__.py"
chown mu2e:mu2e /var/log/monitoring
